version: '3.9'
services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - 56782:5672
      - 15682:15672
    environment:
      RABBITMQ_DEFAULT_VHOST: go-boiler
      RABBITMQ_DEFAULT_USER: go-boiler-user
      RABBITMQ_DEFAULT_PASS: go-boiler-password
    volumes:
      - rabbitmq_data:/bitnami

  main-db-postgres:
    container_name: 'main-db-postgres'
    restart: always
    image: 'postgres:12.9'
    volumes:
      - main-db-data:/var/lib/postgresql/data
      - ./docker/main-db/init.d:/docker-entrypoint-initdb.d
    ports:
      - 5441:5432
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go-boiler-main-db
    networks:
      - some-net

volumes:
  rabbitmq_data:
  main-db-data:

networks:
  some-net:
    driver: bridge